'use strict';
const english={
'УКРМЕХІНВЕСТ — Захисні металеві конструкції':'UKRMEKHINVEST — Protective metal structures',
'Захисні двері, віконниці та металеві жалюзі. Українське виробництво в Івано-Франківській області. Індивідуальні замовлення.':'Protective doors, shutters and metal blinds. Made in Ukraine’s Ivano-Frankivsk region. Custom orders.',
'До вмісту':'Skip to content','УКРМЕХІНВЕСТ':'UKRMEKHINVEST','Пропустити ↗':'Skip ↗','УКРМЕХІНВЕСТ — на початок':'UKRMEKHINVEST — home','Основна навігація':'Main navigation',
'Продукція':'Products','Застосування':'Applications','Про компанію':'About us','Контакти':'Contact','Безкоштовна консультація':'Free consultation','Відкрити меню':'Open menu','Закрити меню':'Close menu',
'Темні захисні металеві жалюзі на сірій цегляній стіні':'Dark protective metal blinds on a grey brick wall','ВИРОБНИЦТВО МЕТАЛЕВИХ КОНСТРУКЦІЙ':'METAL STRUCTURE MANUFACTURING','Захисні':'Protective','металеві':'metal','конструкції':'structures',
'Виготовляємо захисні двері, віконниці та жалюзі для громадських і приватних об’єктів. Приймаємо індивідуальні замовлення.':'We manufacture protective doors, shutters and blinds for public and private buildings. Custom orders welcome.',
'Записатися на безкоштовну консультацію':'Book a free consultation','Переглянути продукцію':'Explore our products','Україна · Івано-Франківська область':'Ukraine · Ivano-Frankivsk region','ГОРТАЙТЕ ВНИЗ ↓':'SCROLL DOWN ↓',
'01 / ПРОДУКЦІЯ':'01 / PRODUCTS','Рішення для':'Solutions for','захисту об’єктів':'building protection','Конструкції для різних типів приміщень і завдань.':'Structures for a range of buildings and requirements.',
'карусель':'carousel','Наша продукція':'Our products','Захисні металеві двері':'Protective metal doors','Захисні двері':'Protective doors','Металеві двері для приміщень, де потрібне захисне рішення. Параметри узгоджуються під конкретний об’єкт.':'Metal doors for spaces that require a protective solution. Specifications are agreed to suit each building.',
'Обговорити замовлення ↗':'Discuss your order ↗','Відкриті захисні металеві віконниці':'Open protective metal shutters','Віконниці':'Window shutters','Захисні металеві конструкції для віконних прорізів. Виготовляються з урахуванням розмірів і потреб замовника.':'Protective metal structures for window openings. Manufactured to the customer’s dimensions and requirements.',
'Металеві жалюзі на цегляній стіні':'Metal blinds on a brick wall','Металеві жалюзі':'Metal blinds','Металеві жалюзі для громадських і приватних приміщень. Рішення підбирають відповідно до місця застосування.':'Metal blinds for public and private spaces. Each solution is selected to suit its intended location.',
'Вибір продукції':'Choose a product','Попередній товар':'Previous product','Наступний товар':'Next product','02 / ЗАСТОСУВАННЯ':'02 / APPLICATIONS','Для різних':'For a range of','типів об’єктів':'building types','Підбираємо конструкцію відповідно до призначення приміщення та потреб замовника.':'We select each structure to suit the purpose of the building and the customer’s requirements.',
'Укриття':'Shelters','Навчальні заклади':'Educational facilities','Медичні заклади':'Healthcare facilities','Офіси':'Offices','Приватні помешкання':'Private homes','03 / ПРО КОМПАНІЮ':'03 / ABOUT US','Практичний підхід':'A practical approach','до кожного об’єкта':'to every building',
'Українське':'Ukrainian','виробництво':'manufacturing','Виготовляємо металеві конструкції в Івано-Франківській області.':'We manufacture metal structures in Ukraine’s Ivano-Frankivsk region.','Індивідуальні':'Custom','замовлення':'orders','Узгоджуємо рішення під потреби конкретного об’єкта.':'We tailor each solution to the requirements of the building.','Різні сфери':'A range of','застосування':'applications','Продукція для громадських установ, бізнесу й приватних приміщень.':'Products for public institutions, businesses and private spaces.',
'04 / ЗВЕРНЕННЯ':'04 / GET IN TOUCH','Обговорімо':'Let’s discuss','ваше замовлення':'your order','Запишіться на безкоштовну консультацію: залиште ім’я та номер телефону.':'Book a free consultation: leave your name and phone number.','Ім’я':'Name','Як до вас звертатися?':'Your name','Телефон':'Phone',
'ЗВ’ЯЗОК':'CONTACT','АДРЕСА':'ADDRESS','Україна, Івано-Франківська область':'Ukraine, Ivano-Frankivsk region','с. Ямниця, вул. Галицька, 58':'58 Halytska Street, Yamnytsia','Навігація внизу':'Footer navigation','ТОВ «УКРМЕХІНВЕСТ»':'UKRMEKHINVEST LLC','На початок ↑':'Back to top ↑',
'Вкажіть ім’я та коректний номер телефону.':'Please enter your name and a valid phone number.','Надсилаємо…':'Sending…','Заявку надіслано':'Request sent','Не вдалося надіслати. Зателефонуйте нам.':'Unable to send. Please call us.'
};
let language='uk';
function t(text){return language==='en'?(english[text]||text):text}
const textItems=[];const walker=document.createTreeWalker(document.documentElement,NodeFilter.SHOW_TEXT);let node;
while(node=walker.nextNode()){if(['SCRIPT','STYLE'].includes(node.parentElement?.tagName))continue;const key=node.textContent.trim();if(english[key])textItems.push({node,key,original:node.textContent})}
const attrs=[];document.querySelectorAll('*').forEach(el=>['alt','aria-label','aria-roledescription','placeholder','content'].forEach(attr=>{const key=el.getAttribute(attr);if(english[key])attrs.push({el,attr,key})}));
function setStatus(key){const el=document.querySelector('#form-status');el.dataset.message=key;el.textContent=t(key)}
function setLanguage(lang){language=lang==='en'?'en':'uk';document.documentElement.lang=language;textItems.forEach(({node,key,original})=>node.textContent=original.replace(key,t(key)));attrs.forEach(({el,attr,key})=>el.setAttribute(attr,t(key)));document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===language)));const status=document.querySelector('#form-status');if(status.dataset.message)status.textContent=t(status.dataset.message);const menu=document.querySelector('.menu');menu.setAttribute('aria-label',t(menu.getAttribute('aria-expanded')==='true'?'Закрити меню':'Відкрити меню'));try{localStorage.setItem('ukm-language',language)}catch{}}
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.lang)));
let saved='uk';try{saved=localStorage.getItem('ukm-language')||'uk'}catch{}setLanguage(saved);
