'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
$('#year').textContent=new Date().getFullYear();
const menu=$('.menu'),nav=$('#nav');function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label',t('Відкрити меню'));menu.textContent='☰'}menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',t(open?'Закрити меню':'Відкрити меню'));menu.textContent=open?'×':'☰'};nav.querySelectorAll('a').forEach(a=>a.onclick=closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu()}});
function scrollUpdate(){const max=document.documentElement.scrollHeight-innerHeight;$('.progress').style.transform=`scaleX(${max>0?scrollY/max:0})`}addEventListener('scroll',scrollUpdate,{passive:true});addEventListener('resize',()=>{scrollUpdate();if(innerWidth>800)closeMenu()});scrollUpdate();
if(!reduced&&'IntersectionObserver'in window){document.body.classList.add('motion');const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(e=>obs.observe(e))}
const slides=$$('.slide'),tabs=$$('.tabs button');let index=0;function show(i){index=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.hidden=n!==index);tabs.forEach((b,n)=>{if(n===index)b.setAttribute('aria-current','true');else b.removeAttribute('aria-current')});$('#counter').textContent=`0${index+1} / 03`}
$('#prev').onclick=()=>show(index-1);$('#next').onclick=()=>show(index+1);tabs.forEach((b,n)=>b.onclick=()=>show(n));$('.slider').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();show(index+(e.key==='ArrowRight'?1:-1))}});let start=null;$('.slider').addEventListener('pointerdown',e=>{if(!e.target.closest('button,a'))start={x:e.clientX,y:e.clientY}});$('.slider').addEventListener('pointerup',e=>{if(start){const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy))show(index+(dx<0?1:-1));start=null}});$('.slider').addEventListener('pointercancel',()=>start=null);
$('#request-form').addEventListener('submit',async function(e){e.preventDefault();if(!this.reportValidity())return;const name=$('#name').value.trim(),phone=$('#phone').value.trim();if(!name||phone.replace(/\D/g,'').length<7){setStatus('Вкажіть ім’я та коректний номер телефону.');return}const button=this.querySelector('button');button.disabled=true;button.setAttribute('aria-busy','true');setStatus('Надсилаємо…');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch('/api/notify-wa',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({name,phone}),signal:controller.signal});if(!response.ok||!(response.headers.get('content-type')||'').includes('application/json'))throw Error('Failed');const result=await response.json();if(result.success===false||result.ok===false||result.error)throw Error('Failed');setStatus('Заявку надіслано');this.reset()}catch{setStatus('Не вдалося надіслати. Зателефонуйте нам.')}finally{clearTimeout(timer);button.disabled=false;button.removeAttribute('aria-busy')}});
